spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zzb1362156
    url: jdbc:mysql://hearthstone-database.c5ameasy6nf8.ap-northeast-1.rds.amazonaws.com/hearthstone
#    url: jdbc:mysql:///hearthstone
server:
  port: 8080
